# Services required for Drupal Development - Nginx, PHP-FPM, MySQL, Mailhog, Portainer

version: '2'

services:

# Nginx container.
  drupal-nginx:
    container_name: drupal-nginx
    image: nginx:latest
    ports:
      - 80:80
    links:
      - drupal-php
    volumes:
      - .:/var/www:rw,delegated
      - ./conf/nginx/default.vhost.conf:/etc/nginx/conf.d/default.conf

# PHP-FPM container.
  drupal-php:
    container_name: drupal-php
    image: supermassive/drupal-docker-php-fpm
    ports:
      - 9001:9001
      - 9000:9000
    links:
      - drupal-mysql
      - drupal-mailhog
    environment:
     - XDEBUG_CONFIG=${XDEBUG_CONFIG}
     - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
    volumes:
      - .:/var/www:rw,delegated
    volumes_from:
      - drupal-mysql

# MySQL container.
  drupal-mysql:
    container_name: drupal-mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
     - MYSQL_DATABASE=${MYSQL_DATABASE}
     - MYSQL_USER=${MYSQL_USER}
     - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./mysql-data:/var/lib/mysql
      - /usr/bin

# Phpmyadmin container.
  drupal-phpmyadmin:
    container_name: drupal-phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    links:
      - drupal-mysql
    environment:
      - PMA_HOST=${PMA_HOST}
      - PMA_PORT=${PMA_PORT}

# Mailhog Container
  drupal-mailhog:
    image: mailhog/mailhog
    container_name: drupal-mailhog
    working_dir: /home/mailhog
    ports:
      - 1025:1025
      - 8025:8025

# Portainer Container
  drupal-portainer:
    container_name: drupal-portainer
    image: portainer/portainer
    ports:
      - 9002:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

volumes:
  portainer: